pipeline {
    agent any
    
    stages {
        stage ('Compile stage')
        {
            steps {
            withMaven(maven : 'maven_3_5_4')
            {
            sh 'mvn -f cluster-example/pom.xml clean compile'
                
            }
        }
    }
    
    stage ('Testing Stage')
    {
        steps {
            withMaven(maven : 'maven_3_5_4')
            {
            sh 'mvn -f cluster-example/pom.xml test'
            }
        }
    }
    
     stage ('Deployment Stage')
    {
        steps {
            withMaven(maven : 'maven_3_5_4')
            {
            sh 'mvn -f cluster-example/pom.xml deploy'
            }
        }
    }
    
  }
    
}
